[project]
name = "REVEX"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "authx>=1.5.1",
    "dedoc>=2.6.1",
    "fastapi-hypermodel>=2.2.0",
    "fastapi[standard]>=0.129.0",
    "pylti1p3>=2.0.0",
    "redis>=7.2.0",
    "sqlalchemy>=2.0.46",
    "structlog>=25.5.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]

[tool.uv]
override-dependencies = [
    "starlette>=0.40.0",
    "fastapi>=0.129.0",
    "itsdangerous>=2.2.0",
    "uvicorn>=0.30.0",
    "python-multipart>=0.0.9",
    "charset-normalizer>=3.4.0",
]


[project.scripts]
dev = "main:run_dev"
prod = "main:run_prod"

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.4",
]
