events {}

http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    sendfile      on;

    client_max_body_size 32m;

    upstream backend_server {
        server host.docker.internal:8000;
        keepalive 32;
    }

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;

            expires 7d;
            add_header Cache-Control "public, max-age=604800";
        }

        location /api/ {
            proxy_pass http://backend_server;

            proxy_set_header Host                $http_host;
            proxy_set_header X-Real-IP           $remote_addr;
            proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto   $scheme;

            proxy_read_timeout 300;
        }

        location /lti/ {
            proxy_pass http://backend_server;

            proxy_set_header Host                $http_host;
            proxy_set_header X-Real-IP           $remote_addr;
            proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto   $scheme;
        }


        location /files/ {
            proxy_pass http://backend_server;

            proxy_set_header Host                $http_host;
            proxy_set_header X-Real-IP           $remote_addr;
            proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto   $scheme;

            proxy_read_timeout 300;
        }

        location /images/ {
            root /usr/share/nginx/static;
            autoindex off;
            try_files $uri @backend_images;

            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        location @backend_images {
            proxy_pass http://backend_server;
            proxy_set_header Host              $http_host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_intercept_errors on;
            error_page 404 = 404;
        }
    }
}
