"""add template with elements

Revision ID: 5fd998dc9b46
Revises: 72ac57963cbd
Create Date: 2026-03-20 23:28:00.400122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fd998dc9b46'
down_revision: Union[str, Sequence[str], None] = '72ac57963cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_templates_course_draft_created', 'templates', ['course_id', 'is_draft', 'created_at'], unique=False)
    op.create_table('template_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('parent_element_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('display_mode', sa.String(length=32), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_element_id'], ['template_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_te_template_order', 'template_elements', ['template_id', 'order'], unique=False)
    op.create_index('idx_te_template_parent_order', 'template_elements', ['template_id', 'parent_element_id', 'order'], unique=False)
    op.create_index('idx_te_template_type', 'template_elements', ['template_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_te_template_type', table_name='template_elements')
    op.drop_index('idx_te_template_parent_order', table_name='template_elements')
    op.drop_index('idx_te_template_order', table_name='template_elements')
    op.drop_table('template_elements')
    op.drop_index('idx_templates_course_draft_created', table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
