"""lti identity payload

Revision ID: 72ac57963cbd
Revises: 
Create Date: 2026-02-25 23:30:23.115446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ac57963cbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('lti_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('lti_context_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['lti_platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'lti_context_id')
    )
    op.create_table('lti_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('lti_user_id', sa.String(length=255), nullable=False),
    sa.Column('is_accept_policy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['lti_platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'lti_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lti_users')
    op.drop_table('lti_courses')
    op.drop_table('lti_platforms')
    # ### end Alembic commands ###
