"""add comments

Revision ID: 8e3d8d2fdd60
Revises: 17d00414122b
Create Date: 2026-05-09 18:00:42.643455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3d8d2fdd60'
down_revision: Union[str, Sequence[str], None] = '17d00414122b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('comment', sa.Text(), nullable=True))
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.NUMERIC(),
                              type_=sa.UUID(),
                              existing_nullable=False)
        batch_op.alter_column('template_id',
                              existing_type=sa.NUMERIC(),
                              type_=sa.UUID(),
                              existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('template_id',
                              existing_type=sa.UUID(),
                              type_=sa.NUMERIC(),
                              existing_nullable=False)
        batch_op.alter_column('id',
                              existing_type=sa.UUID(),
                              type_=sa.NUMERIC(),
                              existing_nullable=False)

    op.drop_column('answers', 'comment')
    # ### end Alembic commands ###