"""add reports with answers

Revision ID: df5a1987e179
Revises: 3dff80f27281
Create Date: 2026-04-06 17:14:39.680419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from report.schemas.report_status import ReportStatusType

# revision identifiers, used by Alembic.
revision: str = 'df5a1987e179'
down_revision: Union[str, Sequence[str], None] = '3dff80f27281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('status', ReportStatusType(), nullable=False),
    sa.Column('grader_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score >= 0.0 AND score <= 1.0', name='ck_reports_score_range'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('reports_author_id_template_id_created_at_idx', 'reports', ['author_id', 'template_id', 'created_at'], unique=False)
    op.create_index('reports_template_id_created_idx', 'reports', ['template_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('element_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('pre_grade', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['template_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_element_id'), 'answers', ['element_id'], unique=False)
    op.create_index(op.f('ix_answers_report_id'), 'answers', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_report_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_element_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('reports_template_id_created_idx', table_name='reports')
    op.drop_index('reports_author_id_template_id_created_at_idx', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
